In [2]:
import pandas as pd
import numpy as np

In [3]:
dane = pd.read_excel('dane harcerek.xlsx', sheet_name='daneSQL')

In [4]:
dane = dane.replace('-', np.nan)

In [5]:
dane.head()

,imię,nazwisko,data urodzenia,PESEL,miejscowość,adres zamieszkania,kod pocztowy,imię matki,imię ojca,tel matki,tel ojca,mail do rodzica,choroby,szkoła,zastęp
0,Ania,Pawlak,31.10.2013 r.,13303102029,Gdynia,Dedela 2/1/6,81-197,Barbara,Robert,503382546,501398277,basiap224@wp.pl,NaN,sp 28 Babie D.,Apatura Iris
1,Tosia,Rudzka,19.01.2010 r.,10211907067,Gdynia,Czwartaków 3/23,81-115,Ewa,Tomasz,503128205,533454908,ewarudzka37@gmail.com,"AZS, choroba lokomocyjna, aparat ortodontyczny...",katolik,Apatura Iris
2,Dorota,Guza,06.07.2010 r.,10270606246,Gdynia,Złota 13,81-154,Monika,Remigiusz,692834642,500051035,rguza@wp.pl,"sierść konia, kota, świnka morska, orzeczenie ...",sp 33 Gdynia,Apatura Iris
3,Ania,Żukowska,07.02.2010 r.,10220700907,Gdynia,Dickmana 53R/2,81-109,Alicja,Marcin,506026200,513093073,zukowska.alicja@gmail.com,NaN,katolik,Apatura Iris
4,Oliwia,Junko,01.02.2010 r.,10220103489,Gdynia,Bosmańska 41B/1,81-116,Beata,Grzegorz,691636163,504803478,beata2187@op.pl,NaN,sp 33 Gdynia,Apatura Iris

In [6]:
tabela_adres = dane.loc[:,['adres zamieszkania', 'kod pocztowy', 'miejscowość']].drop_duplicates('adres zamieszkania').reset_index(drop=True)

In [7]:
tabela_adres

     adres zamieszkania kod pocztowy  miejscowość
0          Dedela 2/1/6       81-197       Gdynia
1       Czwartaków 3/23       81-115       Gdynia
2              Złota 13       81-154       Gdynia
3        Dickmana 53R/2       81-109       Gdynia
4       Bosmańska 41B/1       81-116       Gdynia
5     Australijska 3E/2       81-116       Gdynia
6          Unruga 70A/6       81-181       Gdynia
7        Podgórska 3F/2       81-166       Gdynia
8            Wiejska 35       81-198      Pogórze
9    Twardowskiego 16/1       81-198      Pogórze
10       Włókiennicza 4       84-230        Rumia
11         Olchowa 40/1       81-198        Mosty
12          Kujawska 24       81-198         Rewa
13  Paderewskiego 19/26       81-198      Pogórze
14             Leśna 36       81-198        Mosty
15         Perłowa 4A/2       81-198  Pierwoszyno
16       Modrzewiowa 16       81-198        Mosty
17       Błękitna 1C/33       81-111       Gdynia
18           Okrężna 10       81-198        Mosty
19         Deszczowa 18       81-198        Mosty
20           Szkolna 2C       81-198        Mosty
21           Olchowa 39       81-198        Mosty
22         Nadmorska 31       81-198   Mechelinki
23       Modrzewiowa 28       81-198        Mosty
24       Paprykowa 35/2       81-198    Dębogórze

In [8]:
#tabela_adres
for idx in range(tabela_adres.shape[0]):
    adres_zam, kod, miejscowosc = tabela_adres.iloc[:,0], tabela_adres.iloc[:,1], tabela_adres.iloc[:,2]
    ulica, numer = adres_zam[idx].split(' ')
    print(f"insert into adres(id_adres, ulica, numer, kod, miejscowosc) values ({idx+1}, '{ulica}', '{numer}', '{kod[idx]}', '{miejscowosc[idx]}');")

insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (1, 'Dedela', '2/1/6', '81-197', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (2, 'Czwartaków', '3/23', '81-115', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (3, 'Złota', '13', '81-154', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (4, 'Dickmana', '53R/2', '81-109', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (5, 'Bosmańska', '41B/1', '81-116', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (6, 'Australijska', '3E/2', '81-116', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (7, 'Unruga', '70A/6', '81-181', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (8, 'Podgórska', '3F/2', '81-166', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (9, 'Wiejska', '35', '81-198', 'Pogórze');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (10, 'Twardowskiego', '16/1', '81-198', 'Pogórze');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (11, 'Włókiennicza', '4', '84-230', 'Rumia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (12, 'Olchowa', '40/1', '81-198', 'Mosty');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (13, 'Kujawska', '24', '81-198', 'Rewa');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (14, 'Paderewskiego', '19/26', '81-198', 'Pogórze');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (15, 'Leśna', '36', '81-198', 'Mosty');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (16, 'Perłowa', '4A/2', '81-198', 'Pierwoszyno');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (17, 'Modrzewiowa', '16', '81-198', 'Mosty');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (18, 'Błękitna', '1C/33', '81-111', 'Gdynia');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (19, 'Okrężna', '10', '81-198', 'Mosty');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (20, 'Deszczowa', '18', '81-198', 'Mosty');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (21, 'Szkolna', '2C', '81-198', 'Mosty');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (22, 'Olchowa', '39', '81-198', 'Mosty');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (23, 'Nadmorska', '31', '81-198', 'Mechelinki');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (24, 'Modrzewiowa', '28', '81-198', 'Mosty');
insert into adres(id_adres, ulica, numer, kod, miejscowosc) values (25, 'Paprykowa', '35/2', '81-198', 'Dębogórze');

In [9]:
tabela_dane = dane.loc[:, ['imię', 'nazwisko', 'PESEL', 'data urodzenia', 'adres zamieszkania']]

In [10]:
np.where(tabela_adres['adres zamieszkania'] == tabela_dane.loc[idx, 'adres zamieszkania'])[0][0]

18

In [11]:
def check_pesel(pesel):
    if len(str(pesel)) != 11:
        return f'0{pesel}'
    else:
        return str(pesel)

In [12]:
for idx in range(tabela_dane.shape[0]):
    print(f"insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values ({idx+1}, {np.where(tabela_adres['adres zamieszkania'] == tabela_dane.loc[idx, 'adres zamieszkania'])[0][0]+1}, '{tabela_dane.loc[idx, 'imię']}', '{tabela_dane.loc[idx, 'nazwisko']}', '{check_pesel(tabela_dane.loc[idx, 'PESEL'])}', '{tabela_dane.loc[idx, 'data urodzenia'].split(' ')[0].replace('.', '-')}');")

insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (1, 1, 'Ania', 'Pawlak', '13303102029', '31-10-2013');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (2, 2, 'Tosia', 'Rudzka', '10211907067', '19-01-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (3, 3, 'Dorota', 'Guza', '10270606246', '06-07-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (4, 4, 'Ania', 'Żukowska', '10220700907', '07-02-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (5, 5, 'Oliwia', 'Junko', '10220103489', '01-02-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (6, 5, 'Patrycja ', 'Junko', '12251300486', '13-05-2012');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (7, 6, 'Maja', 'Princ', '10230903226', '09-03-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (8, 7, 'Joanna', 'Kochańska', '13302605363', '26-10-2013');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (9, 7, 'Anieszka', 'Kochańska', '09222404223', '24-02-2009');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (10, 8, 'Barbara', 'Splitt', '08300305988', '03-10-2008');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (11, 8, 'Aniela', 'Splitt', '13222508740', '25-02-2013');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (12, 9, 'Oriana', 'Sendacka', '13311100624', '11-11-2013');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (13, 9, 'Martyna ', 'Sendacka', '10212707642', '27-01-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (14, 10, 'Oliwia', 'Krause', '10252000381', '20-05-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (15, 11, 'Anastazja ', 'Pawłowska', '09310902008', '09-11-2009');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (16, 11, 'Marta', 'Pawłowska', '12220308208', '03-02-2012');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (17, 12, 'Julia', 'Gołata', '11251901765', '19-05-2011');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (18, 13, 'Nicole', 'Pospieszyńska', '09290209841', '02-09-2009');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (19, 14, 'Amelia', 'Owerczuk', '09213009907', '30-01-2009');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (20, 14, 'Zuzanna', 'Owerczuk', '10281809847', '18-08-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (21, 15, 'Helena', 'Woroniecka', '11282209742', '22-08-2011');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (22, 16, 'Magdalena', 'Antonowicz', '10262910302', '29-06-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (23, 17, 'Zofia', 'Budny', '12210905848', '09-01-2021');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (24, 18, 'Weronika', 'Czarnecka', '09242908361', '29-04-2009');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (25, 19, 'Martyna', 'Tyńska', '09252305107', '23-05-2009');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (26, 20, 'Alicja', 'Żychska', '11251800729', '18-05-2011');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (27, 21, 'Klaudia', 'Żak', '10242002382', '20-04-2010');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (28, 22, 'Kalina', 'Żakowska', '12302006228', '20-10-2012');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (29, 23, 'Lena', 'Kukiełka', '11302507586', '25-10-2011');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (30, 24, 'Joanna', 'Radaszewska', '13241806704', '18-04-2013');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (31, 25, 'Ewa', 'Czyżewska', '13272904985', '29-07-2013');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (32, 1, 'Dorota', 'Pawlak', '07262602720', '26-06-2007');
insert into podstawowe_dane(id_podstawowe_dane, id_adres, imie, nazwisko, PESEL, data_urodzenia) values (33, 8, 'Marysia', 'Splitt', '07210301701', '03-01-2007');

In [13]:
for idx in range(dane.shape[0]):
    print(f"insert into harcerka(id_harcerka, id_podstawowe_dane) values ({idx+1}, {idx+1});")

insert into harcerka(id_harcerka, id_podstawowe_dane) values (1, 1);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (2, 2);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (3, 3);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (4, 4);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (5, 5);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (6, 6);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (7, 7);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (8, 8);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (9, 9);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (10, 10);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (11, 11);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (12, 12);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (13, 13);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (14, 14);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (15, 15);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (16, 16);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (17, 17);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (18, 18);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (19, 19);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (20, 20);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (21, 21);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (22, 22);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (23, 23);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (24, 24);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (25, 25);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (26, 26);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (27, 27);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (28, 28);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (29, 29);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (30, 30);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (31, 31);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (32, 32);
insert into harcerka(id_harcerka, id_podstawowe_dane) values (33, 33);

In [14]:
dane

,imię,nazwisko,data urodzenia,PESEL,miejscowość,adres zamieszkania,kod pocztowy,imię matki,imię ojca,tel matki,tel ojca,mail do rodzica,choroby,szkoła,zastęp
0,Ania,Pawlak,31.10.2013 r.,13303102029,Gdynia,Dedela 2/1/6,81-197,Barbara,Robert,503382546,501398277,basiap224@wp.pl,NaN,sp 28 Babie D.,Apatura Iris
1,Tosia,Rudzka,19.01.2010 r.,10211907067,Gdynia,Czwartaków 3/23,81-115,Ewa,Tomasz,503128205,533454908,ewarudzka37@gmail.com,"AZS, choroba lokomocyjna, aparat ortodontyczny...",katolik,Apatura Iris
2,Dorota,Guza,06.07.2010 r.,10270606246,Gdynia,Złota 13,81-154,Monika,Remigiusz,692834642,500051035,rguza@wp.pl,"sierść konia, kota, świnka morska, orzeczenie ...",sp 33 Gdynia,Apatura Iris
3,Ania,Żukowska,07.02.2010 r.,10220700907,Gdynia,Dickmana 53R/2,81-109,Alicja,Marcin,506026200,513093073,zukowska.alicja@gmail.com,NaN,katolik,Apatura Iris
4,Oliwia,Junko,01.02.2010 r.,10220103489,Gdynia,Bosmańska 41B/1,81-116,Beata,Grzegorz,691636163,504803478,beata2187@op.pl,NaN,sp 33 Gdynia,Apatura Iris
5,Patrycja,Junko,13.05.2012 r.,12251300486,Gdynia,Bosmańska 41B/1,81-116,Beata,Grzegorz,691636163,504803478,beata2187@op.pl,NaN,sp 33 Gdynia,Apatura Iris
6,Maja,Princ,09.03.2010 r.,10230903226,Gdynia,Australijska 3E/2,81-116,Justyna,Przemysław,609323525,605489447,justynapikus@wp.pl,NaN,sp 33 Gdnia,Apatura Iris
7,Joanna,Kochańska,26.10.2013 r.,13302605363,Gdynia,Unruga 70A/6,81-181,Regina,Andrzej,605056914,729968579,rkochanska@gmail.com,czerwony barwnik,katolik,Leśne Dzwonki
8,Anieszka,Kochańska,24.02.2009 r.,9222404223,Gdynia,Unruga 70A/6,81-181,Regina,Andrzej,605056914,729968579,rkochanska@gmail.com,NaN,katolik,Leśne Dzwonki
9,Barbara,Splitt,03.10.2008 r.,8300305988,Gdynia,Podgórska 3F/2,81-166,Dorota,Sławomir,500073388,501835934,gerdora@op.pl,"pyłki, sierść, kurz (Clatra)",NaN,Leśne Dzwonki
10,Aniela,Splitt,25.02.2013 r.,13222508740,Gdynia,Podgórska 3F/2,81-166,Dorota,Sławomir,500073388,501835934,gerdora@op.pl,NaN,katolik,Leśne Dzwonki
11,Oriana,Sendacka,11.11.2013 r.,13311100624,Pogórze,Wiejska 35,81-198,Weronika,Piotr,504248394,504394122,weronikasendacka@gmail.com,NaN,katolik,Leśne Dzwonki
12,Martyna,Sendacka,27.01.2010 r.,10212707642,Pogórze,Wiejska 35,81-198,Weronika,Piotr,504248394,504394122,weronikasendacka@gmail.com,NaN,katolik,Leśne Dzwonki
13,Oliwia,Krause,20.05.2010 r.,10252000381,Pogórze,Twardowskiego 16/1,81-198,Karolina,NaN,604658954,NaN,karolka.krause@gmail.com,NaN,sp Pogórze,Leśne Dzwonki
14,Anastazja,Pawłowska,09.11.2009 r.,9310902008,Rumia,Włókiennicza 4,84-230,Anna,Artur,660542523,694136793,radzkaa@o2.pl,NaN,NaN,Leśne Dzwonki
15,Marta,Pawłowska,03.02.2012 r.,12220308208,Rumia,Włókiennicza 4,84-230,Anna,Artur,660542523,694136793,radzkaa@o2.pl,choroba lokomocyjna,NaN,Leśne Dzwonki
16,Julia,Gołata,19.05.2011 r.,11251901765,Mosty,Olchowa 40/1,81-198,Karolina,Tomasz,797426286,780118728,tomaszgolata@gmail.com,NaN,sp Pogórze,Leśne Dzwonki
17,Nicole,Pospieszyńska,02.09.2009 r.,9290209841,Rewa,Kujawska 24,81-198,Edyta,Czesław,501416520,507218209,czeslaw31@interia.pl,lokomocyjna,plastyk,Irysy
18,Amelia,Owerczuk,30.01.2009 r.,9213009907,Pogórze,Paderewskiego 19/26,81-198,Ilona,Marcin,571458136,NaN,il-ona@wp.pl,okulary,katolik,Irysy
19,Zuzanna,Owerczuk,18.08.2010 r.,10281809847,Pogórze,Paderewskiego 19/26,81-198,Ilona,Marcin,571458136,NaN,il-ona@wp.pl,NaN,katolik,Irysy
20,Helena,Woroniecka,22.08.2011 r.,11282209742,Mosty,Leśna 36,81-198,Magdalena,Mariusz,512201287,504387678,woronieckamagdalena@gmail.com,okulary,sp Pogórze,Irysy
21,Magdalena,Antonowicz,29.06.2010 r.,10262910302,Pierwoszyno,Perłowa 4A/2,81-198,Tamara,Henryk,693060486,601131894,hantonowicz@gmail.com,NaN,sp Pogórze,Irysy
22,Zofia,Budny,09.01.2021 r.,12210905848,Mosty,Modrzewiowa 16,81-198,Iwona,Jerzy,602208814,605121073,ipast@op.pl,NaN,sp Pogórze,Irysy
23,Weronika,Czarnecka,29.04.2009 r.,9242908361,Gdynia,Błękitna 1C/33,81-111,Kinga,Karol,668295778,606740557,kingaczarnecka17@gmail.com,alergia pokarmowa,9 LO,Stominajki
24,Martyna,Tyńska,23.05.2009 r.,9252305107,Mosty,Okrężna 10,81-198,Dorota,Marcin,500203621,501642463,dota82@wp.pl,"alergie, oksy, aparat, krwotoki (rupaller; pie...",9 LO,Stominajki
25,Alicja,Żychska,18.05.2011 r.,11251800729,Mosty,Deszczowa 18,81-198,Małgorzata,Marek,509360870,517140939,mzychska@gmail.com,choroba lokomocyjna,sp Mosty,Stominajki
26,Klaudia,Żak,20.04.2010 r.,10242002382,Mosty,Szkolna 2C,81-198,Irma,NaN,788571626,NaN,irmazak@wp.pl,NaN,sp Mosty,Stominajki
27,Kalina,Żakowska,20.10.2012 r.,12302006228,Mosty,Olchowa 39,81-198,Marcjanna,Rafał,500389510,516441589,marcjanna.zakowska@gmail.com,NaN,sp Mosty,Stominajki
28,Lena,Kukiełka,25.10.2011 r.,11302507586,Mechelinki,Nadmorska 31,81-198,Katarzyna,NaN,510794425,NaN,kasiaa-kukielka@wp.pl,NaN,sp Mosty,Stominajki
29,Joanna,Radaszewska,18.04.2013 r.,13241806704,Mosty,Modrzewiowa 28,81-198,Katarzyna,Jacek,667222220,609189504,k.radaszewska@wp.pl,aparat ortodontyczny,sp Dębogórze,Stominajki
30,Ewa,Czyżewska,29.07.2013 r.,13272904985,Dębogórze,Paprykowa 35/2,81-198,Agnieszka,Bartłomiej,737495475,500895410,aczyzewska82@gmail.com,okulary,sp Dębogórze,Stominajki
31,Dorota,Pawlak,26.06.2007 r.,7262602720,Gdynia,Dedela 2/1/6,81-197,Barbara,Robert,503382546,501398277,basiap224@wp.pl,okulary,I LO Sopot,kadra
32,Marysia,Splitt,03.01.2007 r.,7210301701,Gdynia,Podgórska 3F/2,81-166,Dorota,Sławomir,500073388,501835934,gerdora@op.pl,choroba lokomocyjna,XIV LO,kadra